/*
 * shift_parameters.h
 *
 *  Created on: Apr 24, 2022
 *      Author: sebas
 */

#ifndef INC_SHIFT_PARAMETERS_H_
#define INC_SHIFT_PARAMETERS_H_

#define TIME_BASED_SHIFTING_ONLY 0

#define SHIFT_LEVER_PRELOAD_TIME_MS 50

#define LEVER_NEUTRAL_POS_MM 37.0f

#define LEVER_NEUTRAL_TOLERANCE 0.8


#define UPSHIFT_MIN_TIME 70

#define UPSHIFT_EXIT_TIMEOUT_MS 75

#define UPSHIFT_ENTER_TIMEOUT_MS 100

#define UPSHIFT_EXIT_POS_MM 42.8f

#define UPSHIFT_ENTER_POS_MM 43.5f


#define DOWNSHIFT_MIN_TIME 70

#define DOWNSHIFT_EXIT_TIMEOUT_MS 75

#define DOWNSHIFT_ENTER_TIMEOUT_MS 100

#define DOWNSHIFT_EXIT_POS_MM 34.0f

#define DOWNSHIFT_ENTER_POS_MM 31.0f


#define TARGET_RPM_TOLERANCE 0.03f

#define CLUTCH_OPEN_POS_MM 27.0f

#define CLUTCH_SLOW_DROP_FAST_TO_SLOW_EXTRA_MM 3.0f

#define CLUTCH_OPEN_TIMEOUT_MS 300

#define SPARK_RETURN_MS 10

#define FAILED_ENTER_CLUTCH_CLOSE_TIMEOUT_MS 500


#define RPM_ARRAY_SIZE 250
#define WHEEL_SPEED_ARRAY_SIZE 250
#define TRANS_ARR_SIZE 100

#define MAX_RPM 14000
#define MIN_SPARK_CUT_RPM 3000
#define ANTI_STALL_RPM 1700
#define MAX_CRANK_RPM 700

#define MOVING_WHEEL_SPEED_MIN_CUTOFF 2.0f

#define TRANS_TO_ENGINE_RATIO 7.5f

#define WHEEL_TO_TRANS_RATIO 20.0f

#define BUTTON_DEBOUNCE_MS 20

#endif /* INC_SHIFT_PARAMETERS_H_ */
